In [1]:
import numpy as np

In [6]:
# 1 Dimensional Array
a=np.array([1,2,3])
print(a)
a.ndim

[1 2 3]


1

In [8]:
# 2 Dimensional Array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a.ndim

2

In [10]:
a.itemsize

4

In [11]:
a.dtype

dtype('int32')

In [14]:
a=np.array([1,2,3],dtype=np.float64)
print(a)

[1. 2. 3.]


In [15]:
a.itemsize  #Gives 8 as float

8

In [16]:
a.size  #Total number of elements

3

In [17]:
a.shape  #Dimension of matrix

(3,)

In [19]:
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.arange(1,5)

array([1, 2, 3, 4])

In [23]:
np.arange(1,5,2) #Step of 2

array([1, 3])

"Linearly spaced numbers" typically refers to a sequence of numbers that are equally spaced apart.

In [26]:
np.linspace(1,4,10)  #Generate 10 numbers between range which are linerally spaced. 

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [31]:
print(a)
a.shape

[1.+0.j 2.+0.j 3.+0.j]


(3,)

In [30]:
a.reshape(1,3)

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [33]:
a.ravel()      #Make it 1 D array as copy

array([1.+0.j, 2.+0.j, 3.+0.j])

In [37]:
a.min()

(1+0j)

In [36]:
a.max()

(3+0j)

In [44]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [41]:
a.sum()

21

In [42]:
a.sum(axis=0)  #Represents columns

array([5, 7, 9])

In [43]:
a.sum(axis=1)   #Represents rows

array([ 6, 15])

In [46]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
np.std(a)

1.707825127659933

In [48]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [49]:
a+b #Simmilar for - * /

array([[ 6,  8],
       [10, 12]])

In [51]:
a.dot(b)

array([[19, 22],
       [43, 50]])