In [1]:
import numpy as np

In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [8]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for row in a.flatten():  #No need to use 2 for loops
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for 