In [2]:
import numpy as np
import time
import sys

In [5]:
#Python list
l = range(1000)       
print(sys.getsizeof(5)*len(l))

28000


In [7]:
#Numpy array
array = np.arange(1000)        
print(array.size*array.itemsize)

4000


Numpy array takes less space than List.
Numpy takes less less time than Python List.

In [43]:
import numpy as np
import time
import sys
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

python list took:  110.10074615478516
numpy took:  17.006874084472656


In [46]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
