In [1]:
import numpy as np

### Indexing

In [2]:
a= np.array([1,2,3,4])

In [3]:
a[0:2]

array([1, 2])

In [4]:
a[-1]   #Reverse Index

4

In [7]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
b[1,2]  #Starts with 0             # row,col

6

In [9]:
b[-1]

array([7, 8, 9])

In [10]:
b[0:2,2]

array([3, 6])

In [11]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
for row in b:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
for cell in b.flat:   #Flats it to 1D array
    print(cell)

1
2
3
4
5
6
7
8
9


In [18]:
a=np.arange(9).reshape(3,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Stacking

In [20]:
np.vstack((a,b))  #Vertical Stacking

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.hstack((a,b))  #Horizontal Stacking

array([[0, 1, 2, 1, 2, 3],
       [3, 4, 5, 4, 5, 6],
       [6, 7, 8, 7, 8, 9]])

In [27]:
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### Slicing

In [30]:
result = np.hsplit(a,3)
print(result)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [31]:
result[0]

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]])

In [33]:
result=np.vsplit(a,2)
print(result)

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])]


In [34]:
result[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [36]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
b = a>4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [41]:
a[b] #Returns element only if true

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
a[b]=-1
print(a)

[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
